[package]
name = "dyscript"
version = "0.0.0"
keywords = ["script language", "typed", "dynamic"]
authors = ["ds2dy3"]

[lib]
name = "dyscript"
path = "src/lib.rs"

[[bin]]
name = "dy"
path = "src/main.rs"
